from __future__ import annotations

from ._identifiers import EntityId

_NAMES = (
    "ACACIA_BOAT",
    "ACACIA_CHEST_BOAT",
    "ALLAY",
    "AREA_EFFECT_CLOUD",
    "ARMADILLO",
    "ARMOR_STAND",
    "ARROW",
    "AXOLOTL",
    "BAMBOO_CHEST_RAFT",
    "BAMBOO_RAFT",
    "BAT",
    "BEE",
    "BIRCH_BOAT",
    "BIRCH_CHEST_BOAT",
    "BLAZE",
    "BLOCK_DISPLAY",
    "BOGGED",
    "BREEZE",
    "BREEZE_WIND_CHARGE",
    "CAMEL",
    "CAT",
    "CAVE_SPIDER",
    "CHERRY_BOAT",
    "CHERRY_CHEST_BOAT",
    "CHEST_MINECART",
    "CHICKEN",
    "COD",
    "COMMAND_BLOCK_MINECART",
    "COW",
    "CREAKING",
    "CREEPER",
    "DARK_OAK_BOAT",
    "DARK_OAK_CHEST_BOAT",
    "DOLPHIN",
    "DONKEY",
    "DRAGON_FIREBALL",
    "DROWNED",
    "EGG",
    "ELDER_GUARDIAN",
    "ENDERMAN",
    "ENDERMITE",
    "ENDER_DRAGON",
    "ENDER_PEARL",
    "END_CRYSTAL",
    "EVOKER",
    "EVOKER_FANGS",
    "EXPERIENCE_BOTTLE",
    "EXPERIENCE_ORB",
    "EYE_OF_ENDER",
    "FALLING_BLOCK",
    "FIREBALL",
    "FIREWORK_ROCKET",
    "FISHING_BOBBER",
    "FOX",
    "FROG",
    "FURNACE_MINECART",
    "GHAST",
    "GIANT",
    "GLOW_ITEM_FRAME",
    "GLOW_SQUID",
    "GOAT",
    "GUARDIAN",
    "HAPPY_GHAST",
    "HOGLIN",
    "HOPPER_MINECART",
    "HORSE",
    "HUSK",
    "ILLUSIONER",
    "INTERACTION",
    "IRON_GOLEM",
    "ITEM",
    "ITEM_DISPLAY",
    "ITEM_FRAME",
    "JUNGLE_BOAT",
    "JUNGLE_CHEST_BOAT",
    "LEASH_KNOT",
    "LIGHTNING_BOLT",
    "LINGERING_POTION",
    "LLAMA",
    "LLAMA_SPIT",
    "MAGMA_CUBE",
    "MANGROVE_BOAT",
    "MANGROVE_CHEST_BOAT",
    "MARKER",
    "MINECART",
    "MOOSHROOM",
    "MULE",
    "OAK_BOAT",
    "OAK_CHEST_BOAT",
    "OCELOT",
    "OMINOUS_ITEM_SPAWNER",
    "PAINTING",
    "PALE_OAK_BOAT",
    "PALE_OAK_CHEST_BOAT",
    "PANDA",
    "PARROT",
    "PHANTOM",
    "PIG",
    "PIGLIN",
    "PIGLIN_BRUTE",
    "PILLAGER",
    "PLAYER",
    "POLAR_BEAR",
    "PUFFERFISH",
    "RABBIT",
    "RAVAGER",
    "SALMON",
    "SHEEP",
    "SHULKER",
    "SHULKER_BULLET",
    "SILVERFISH",
    "SKELETON",
    "SKELETON_HORSE",
    "SLIME",
    "SMALL_FIREBALL",
    "SNIFFER",
    "SNOWBALL",
    "SNOW_GOLEM",
    "SPAWNER_MINECART",
    "SPECTRAL_ARROW",
    "SPIDER",
    "SPLASH_POTION",
    "SPRUCE_BOAT",
    "SPRUCE_CHEST_BOAT",
    "SQUID",
    "STRAY",
    "STRIDER",
    "TADPOLE",
    "TEXT_DISPLAY",
    "TNT",
    "TNT_MINECART",
    "TRADER_LLAMA",
    "TRIDENT",
    "TROPICAL_FISH",
    "TURTLE",
    "VEX",
    "VILLAGER",
    "VINDICATOR",
    "WANDERING_TRADER",
    "WARDEN",
    "WIND_CHARGE",
    "WITCH",
    "WITHER",
    "WITHER_SKELETON",
    "WITHER_SKULL",
    "WOLF",
    "ZOGLIN",
    "ZOMBIE",
    "ZOMBIE_HORSE",
    "ZOMBIE_VILLAGER",
    "ZOMBIFIED_PIGLIN",
)

def from_id(value: str) -> EntityId:
    return EntityId(value)

for _name in _NAMES:
    globals()[_name] = EntityId(f"minecraft:{_name.lower()}")

VALUES: tuple[EntityId, ...] = tuple(globals()[name] for name in _NAMES)
BY_NAME: dict[str, EntityId] = {name: globals()[name] for name in _NAMES}

__all__ = [
    "BY_NAME",
    "EntityId",
    "VALUES",
    "from_id",
    *_NAMES,
]

del _name
